---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: rclone.csi.veloxpack.io
spec:
  attachRequired: false
  volumeLifecycleModes:
    - Persistent
    - Ephemeral  # Enable inline/ephemeral volumes
  podInfoOnMount: true
  fsGroupPolicy: File  # Enable FSGroupPolicy to allow mounting volumes with specific FSGroup
