apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: DaemonSet
      name: csi-rclone-node
    patch: |-
      - op: add
        path: /spec/template/spec/containers/2/args/-
        value: "--remount"
