# RC API with Service (exposes RC API via Kubernetes Service)
#
# Prerequisites:
#   Create the RC auth secret before applying:
#   kubectl create secret generic csi-rclone-rc-auth \
#     --from-literal=username=admin \
#     --from-literal=password=secure-password \
#     -n veloxpack

namespace: veloxpack

resources:
  - ../../base

components:
  - ../../components/rc-basic
  - ../../components/rc-service

