apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: DaemonSet
      name: csi-rclone-node
    patch: |-
      - op: add
        path: /spec/template/spec/containers/2/args/-
        value: "--rc"
      - op: add
        path: /spec/template/spec/containers/2/args/-
        value: "--rc-addr=:5573"
      - op: add
        path: /spec/template/spec/containers/2/args/-
        value: "--rc-user=$(RC_USERNAME)"
      - op: add
        path: /spec/template/spec/containers/2/args/-
        value: "--rc-pass=$(RC_PASSWORD)"
      - op: add
        path: /spec/template/spec/containers/2/env/-
        value:
          name: RC_USERNAME
          valueFrom:
            secretKeyRef:
              name: csi-rclone-rc-auth
              key: username
      - op: add
        path: /spec/template/spec/containers/2/env/-
        value:
          name: RC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: csi-rclone-rc-auth
              key: password
      - op: add
        path: /spec/template/spec/containers/2/ports
        value:
          - name: rc
            containerPort: 5573
            protocol: TCP

